apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-05-05T11:07:42Z"
  generation: 1
  labels:
    app: sidhantrt
  name: sidhantrt
  namespace: default
  resourceVersion: "1039004"
  uid: 66182806-2ef2-4856-853e-c8405cfc3b24
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sidhantrt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sidhantrt
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

