apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
  namespace: {{ include "nginx.namespace" . }}
  {{- with .Values.nginx.labels }}
  labels:
    {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.nginx.service.port }}
    targetPort: {{ .Values.nginx.service.targetPort }}
  {{- with .Values.nginx.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: {{ .Values.nginx.service.type }}
